- hosts: mikrotik
  gather_facts: false

  tasks:
  - name: add group
    routeros_command:
      commands: /user group add name=ssh policy=ssh,read,write

  - name: add user
    routeros_command:
      commands: /user add name=onotole password=password1 group=ssh  
  
  - name: alow ssh key and password
    routeros_command:
      commands: /ip ssh set always-allow-password-login=yes

  - name: copy pub key
    command: "sshpass -p {{ ansible_ssh_pass }} scp -P {{ ansible_port }} keys/mikrotik.pub {{ ansible_user }}@{{ ansible_host }}:onotole.pub"

