- hosts: mikrotik
  gather_facts: false

  tasks:
  - name: add group
    routeros_command:
      commands: /user group add name=ssh policy=ssh,read,write

  - name: add user
    routeros_command:
      commands: /user add name=onotole password=password1 group=ssh  

  