- hosts: mikrotik
  vars:
    ansible_connection: network_cli
    ansible_network_os: routeros
  gather_facts: false

  tasks:
  - name: add group
    routeros_command:
      commands: /user group add name=ssh policy=ssh,read,write

  - name: add user
    routeros_command:
      commands: /user add name=onotole password=password1 group=ssh  
  
  - name: alow ssh key and password
    routeros_command:
      commands: /ip ssh set always-allow-password-login=yes

- hosts: mikrotik
  vars:
    ansible_connection: ssh
    
  tasks:
  - name: copy pub key
    copy:
      src: keys/mikrotik.pub
      dest: /skins/onotole.pub